Changed related to renaming PolicyMonitor to MonitorTemplate for Policy Management
racker/salus-policy-management pull request #48
Opened 2020-11-02 08:33 UTC by shabd67

# Resolves

[SALUS-1035](https://jira.rax.io/browse/SALUS-1035)

# What

Changes corresponding to rename policy_monitor to monitor_template

2020-11-02 15:19 UTC, jjbuchan requested changes

2020-11-02 15:19 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/policy/manage/services/MonitorPolicyManagement.java
> +  public List<UUID> getEffectiveMonitorPolicyIdsForTenant(String tenantId) {
This is not an accurate name.  The method below is the correct `getEffectiveMonitorPolicyIdsForTenant`

2020-11-02 16:09 UTC, shabd67 commented on src/main/java/com/rackspace/salus/policy/manage/services/MonitorPolicyManagement.java
> +  public List<UUID> getEffectiveMonitorPolicyIdsForTenant(String tenantId) {
@jjbuchan , this method gets all the effective MonitorPolicies For a Tenant, so named it "getEffectiveMonitorPolicyIdsForTenant". isn't that right?

2020-11-02 16:14 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/policy/manage/services/MonitorPolicyManagement.java
> +  public List<UUID> getEffectiveMonitorPolicyIdsForTenant(String tenantId) {
Take a look at what this is doing and then the one below on line 159.  With your change they are both named the same.  Unless they are returning the same data that cannot be correct.

2020-11-02 16:28 UTC, shabd67 commented on src/main/java/com/rackspace/salus/policy/manage/services/MonitorPolicyManagement.java
> +  public List<UUID> getEffectiveMonitorPolicyIdsForTenant(String tenantId) {
is "getEffectiveMonitorIdsUsingTemplatesForTenant" a good name to be used instead of that?

2020-11-03 14:42 UTC, itzg commented on src/main/java/com/rackspace/salus/policy/manage/services/MonitorPolicyManagement.java
> +  public List<UUID> getEffectiveMonitorIdsUsingMonitorPoliciesForTenant(String tenantId) {
Using a concept diagram I created last week to help me review these PRs (and I'll create a docs PR with that), it seems like `getMonitorTemplateIdsForTenant` is a clearer name, but please confirm your interpretation of what the retrieval and stream filtering is doing.

2020-11-03 14:46 UTC, itzg commented on src/main/java/com/rackspace/salus/policy/manage/services/MonitorPolicyManagement.java
> +  public List<UUID> getEffectiveMonitorIdsUsingMonitorPoliciesForTenant(String tenantId) {
Here's that diagram PR

https://github.com/racker/salus-docs/pull/25

2020-11-03 16:12 UTC, shabd67 commented on src/main/java/com/rackspace/salus/policy/manage/services/MonitorPolicyManagement.java
> +  public List<UUID> getEffectiveMonitorIdsUsingMonitorPoliciesForTenant(String tenantId) {
in this case, we are returning monitor ids for all monitor policies linked with a tenant, so named it as "getEffectiveMonitorIdsUsingMonitorPoliciesForTenant".

2020-11-03 16:49 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/policy/manage/services/MonitorPolicyManagement.java
> +  public List<UUID> getEffectiveMonitorIdsUsingMonitorPoliciesForTenant(String tenantId) {
Here's a breakdown of what this method is doing.

```
        // Get all monitor policies that apply to an individual tenant
    return getEffectiveMonitorPoliciesForTenant(tenantId)
        // Convert that list to a stream
        .stream()
        // Get the monitor id from that policy (i.e. the monitor template id)
        .map(MonitorPolicy::getMonitorId)
        // filter out null policies (i.e. opt-out policies)
        .filter(Objects::nonNull)
        // return a list of monitor template ids
        .collect(Collectors.toList());
```

With that, Geoff's suggestion is correct.

Either `getMonitorTemplateIdsForTenant` (assuming that name doesn't conflict with another method) or `getEffectiveMonitorTemplateIdsForTenant` would work for me.

---

Maybe to help make that clearer you could look into what's required to change this field on `MonitorPolicy.java`

from
```
  @Column(name="monitor_id")
  @org.hibernate.annotations.Type(type="uuid-char")
  UUID monitorId;
```
to
```
  @Column(name="monitor_template_id")
  @org.hibernate.annotations.Type(type="uuid-char")
  UUID monitorTemplateId;
```

That change would mean this line changes from:

```
.map(MonitorPolicy::getMonitorId)
```
to
```
.map(MonitorPolicy::getMonitorTemplateId)
```

---

Part of the reason I would like you to have a clearer understanding of what's going on with this is that we still have an issue pending to add Task Policies.  I would like you to be able to take that on sometime in the near future.

2020-11-03 16:58 UTC, jjbuchan requested changes
See my recent comment.

2020-11-19 15:25 UTC, itzg commented on src/main/java/com/rackspace/salus/policy/manage/web/model/MonitorPolicyCreate.java
> +  UUID monitorTemplateId;
This reminds me. Please update any example requests in the Insomnia workspace: https://github.com/racker/salus-telemetry-bundle/blob/master/dev/Insomnia-workspace.yaml

2020-11-19 15:25 UTC, itzg commented on src/test/java/com/rackspace/salus/policy/manage/web/controller/MonitorPolicyApiControllerTest.java
> +    List<MonitorPolicyDTO> listOfPoliciesDTO = listOfPolicies.parallelStream().map(MonitorPolicyDTO::new).collect(Collectors.toList());
Any particular reason for parallel stream?
```suggestion
    List<MonitorPolicyDTO> listOfPoliciesDTO = listOfPolicies.stream().map(MonitorPolicyDTO::new).collect(Collectors.toList());
```

2020-11-19 15:28 UTC, shabd67 commented on src/main/java/com/rackspace/salus/policy/manage/web/model/MonitorPolicyCreate.java
> +  UUID monitorTemplateId;
yes, it will be changed for policy-monitors under Admin Apis as well.

2020-11-19 15:29 UTC, shabd67 commented on src/test/java/com/rackspace/salus/policy/manage/web/controller/MonitorPolicyApiControllerTest.java
> +    List<MonitorPolicyDTO> listOfPoliciesDTO = listOfPolicies.parallelStream().map(MonitorPolicyDTO::new).collect(Collectors.toList());
just thought of performance.

2020-11-19 18:45 UTC, itzg commented on src/test/java/com/rackspace/salus/policy/manage/web/controller/MonitorPolicyApiControllerTest.java
> +    List<MonitorPolicyDTO> listOfPoliciesDTO = listOfPolicies.parallelStream().map(MonitorPolicyDTO::new).collect(Collectors.toList());
In a unit test with a collection of I think 5 elements it isn't worth the thread pool overhead. No need to change this, but always be cautious of pre-optimizing code.

2020-11-19 18:48 UTC, itzg approved these changes

2020-11-23 15:28 UTC, merged