Metadata policy is being cashed even after deletion
racker/salus-policy-management pull request #49
Opened 2020-11-04 14:34 UTC by shabd67

# Resolves

[SALUS-1033](https://jira.rax.io/browse/SALUS-1033)

# What

BugFix - Metadata policy is being cashed even after deletion

# Depends On

https://github.com/racker/salus-telemetry-monitor-management/pull/227
https://github.com/racker/salus-telemetry-model/pull/171

2020-11-04 15:33 UTC, itzg reviewed
Changes here look good, but there's the corresponding request in https://github.com/racker/salus-telemetry-monitor-management/pull/227

2020-11-04 15:33 UTC, itzg commented on src/main/java/com/rackspace/salus/policy/manage/services/PolicyManagement.java
> +@Slf4j
I see you added the logger declaration, but didn't end up using it. If there were debugging/trace logs that you used for your investigation then feel free to leave them. If in doubt about the "quality" of the logs, then make them trace level.

2020-11-04 15:33 UTC, itzg commented on src/main/java/com/rackspace/salus/policy/manage/web/client/PolicyApiClient.java
>  public class PolicyApiClient implements PolicyApi {
There's will be a new method in this class that I have requested over here https://github.com/racker/salus-telemetry-monitor-management/pull/227#discussion_r517428946

2020-11-09 20:28 UTC, jjbuchan requested changes
Moving forward, can you add more of a description to your PRs.  Following our standard template we provide would help provide some more context about why you've done things a certain way.

The "What" section of this PR does not appear to be entirely accurate.  This PR is essentially a refactor not a bugfix.

2020-11-09 20:28 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/policy/manage/web/client/PolicyApi.java
> +  void evictEffectiveMonitorMetadataMap(String tenantId, TargetClassName className,
I do like this refactor  Can you add a similar api client endpoint for all the methods that currently have a `useCache` field and remove all uses of that field.

2020-11-09 20:28 UTC, jjbuchan commented on src/test/java/com/rackspace/salus/policy/manage/web/client/PolicyApiClientTest.java
> +
Can you describe why these test changes were needed and what it is now verifying?

2020-11-09 20:28 UTC, jjbuchan commented on src/test/java/com/rackspace/salus/policy/manage/web/client/PolicyApiClientTest.java
> +
To me it looks like things are not working as expected.

2020-11-20 08:34 UTC, shabd67 commented on src/test/java/com/rackspace/salus/policy/manage/web/client/PolicyApiClientTest.java
> +
after invoking "getEffectiveMonitorMetadataMap" for first time and then evicting that its entry from cache. Once its done, its invoking "getEffectiveMonitorMetadataMap" again in order to add it into cache.

2020-11-20 15:23 UTC, itzg approved these changes

2020-11-23 16:21 UTC, merged